using System;
using System.Data.Common;
using System.Data.SQLite;
using System.IO;
using System.Data;
/*
	Program to smoke test the Sqlite assembly and create the badges database.
	Also seeds the database with a single record and gets the data via the PetaPoco ORM.
*/
namespace SqliteBootstrap
{
	class Program
	{
		static void Main(string[] args)
		{
			// create the file in the documents folder
			String fileName = Path.Combine(Environment.GetFolderPath(System.Environment.SpecialFolder.MyDocuments), "badges.db");
			// create the fil, table and sample if its not there
			SeedDatabase(fileName);
			// display the new record.
			QueryDatabaseOrm(fileName);

            Console.ReadKey();
		}

		private static void QueryDatabaseOrm(string fileName)
		{
			// create a database "context" object t
			String connectionString =  String.Format("Data Source={0}", fileName);

			DbProviderFactory sqlFactory = new System.Data.SQLite.SQLiteFactory();
			PetaPoco.Database db = new PetaPoco.Database(connectionString, sqlFactory);
			// For Sql Server replace the lines above with the two lines below
			//String connectionString =  @"data source=[Server];initial catalog=[Database];user id=[USER];password=[******];";
			//PetaPoco.Database db = new PetaPoco.Database(connectionString, "System.Data.SqlClient");

			// load and array of POCO for Badges
			String sql = "select * from Badges";
			foreach (Badge rec in db.Query<Badge>(sql))
			{
				Console.WriteLine("{0} {1} {2} {3}", rec.Id, rec.Title, rec.Description, rec.Level);
			}
		}
		//
		// Create the SQLite database and file. 
		//
		private static void SeedDatabase(string fileName)
		{
			String dbConnection = String.Format("Data Source={0}", fileName);
			String sql = @"
create table if not exists [Badges] (
[Id] INTEGER PRIMARY KEY ASC,
[Title] varchar(20) ,
[Description] varchar(255),
[Level] int)";
			ExecuteNonQuery(dbConnection, sql);
			Console.WriteLine("Created {0}", fileName);
			
			sql = @"
insert or replace into Badges ([Id], [Title], [Description], [Level]) 
     values (1, 'Site MVP', 'Awarded to members who contribute often and wisely', 2);
";
			ExecuteNonQuery(dbConnection, sql);
			Console.WriteLine("Seeded database with a sample record");
		}

		// Helper extracted from SqliteHelper.cs
		public static int ExecuteNonQuery(string dbConnection, string sql)
		{
			SQLiteConnection cnn = new SQLiteConnection(dbConnection);
			try
			{
				cnn.Open();
				SQLiteCommand mycommand = new SQLiteCommand(cnn);
				mycommand.CommandText = sql;
				int rowsUpdated = mycommand.ExecuteNonQuery();
				return rowsUpdated;
			}
			catch (Exception fail)
			{
				Console.WriteLine(fail.Message);
				return 0;
			}
			finally
			{
				cnn.Close();
			}
		}
	}

	//
    // PetaPoco to SQL Class for table Badges
	// generated by DbViewSharp http://dbviewsharp.codeplex.com
	// 
	// Note the attributes are probably not all necessary as the table was designed
	// to be ORM-friendly. However they are included as a hint for how to use them
	// when creating an object mapping to a legacy table.
	// See Petapoco documentation for more help. http://www.toptensoftware.com/petapoco/
	// the class is partial so you can implement other behaviours separate from the Petapoco 
	// requirements.
	// Note: the Id type must be Int64 for self-generating keys in Sqlite.
	// 
    [PetaPoco.TableName("Badges")]
    [PetaPoco.PrimaryKey("Id")]
    public partial class Badge
    {
        [PetaPoco.Column("Id")] public Int64 Id {get; set;}
        [PetaPoco.Column("Title")] public String Title {get; set;}
        [PetaPoco.Column("Description")] public String Description {get; set;}
        [PetaPoco.Column("Level")] public Int32? Level {get; set;}
    }

}

